### ISSUE TITLE
Question about usage of named Docker volumes

### ISSUE THREAD

**Issue by benibr** [ucphhpc/docker-migrid#36]
The current usage of the Docker volumes is:

* Data is stored in directories inside the repo (state, mig, certs, etc.) and not within Dockers own structure (/var/lib/docker/volumes)
* These directories might get removed by make targets like clean or distclean
* Named Docker volumes are created via docker compose, with the above mentioned directories as targets
* Those named volumes are then assigned to containers
* The named volumes are never cleaned up by any make targets

In some corner cases this leads to unwanted behaviour:

* If the target path of a volume should change, the volume is not recreated automatically, thus after rebuilding everything the containers run with the old volume
* Same happens if the path of the docker-migrid repository changes
* In both cases the wrong path is not visible in the docker-migrid repo, only if one inspects the existing volumes
* Deleting the named volumes does not delete the data, unlike one might expect

I would like to the discuss the option of completely removing the named volumes and setting the bindmounts only in the volumes list of each container. This would result in

* no more hidden leftovers after `make distclean`
* no more manual cleanup necessary if directories are changed
* possibility to see what is mounted whereto in the compose section of each container
* removal of 400 lines in docker-migrid, resulting in better readability

**Comment by benibr** [comment]
For clearification, an example of the change would look like this:

Before:
```
services:
  migrid:
    ...
    volumes:
      - type: volume
        source: httpd
        target: /etc/httpd/
volumes:
  httpd:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_MIGRID_ROOT}/httpd
      o: bind
```

After:

```
services:
  migrid:
  ...
  volumes:
    - ${DOCKER_MIGRID_ROOT}/httpd:/etc/httpd/
```

I already have I prepared change, if there's interest, I can open a PR.
